[package]
name = "kjql"
version = "1.0.0"
edition = "2021"
authors = ["klion26 <klion26@apache.org>"]
exclude = ["rustfmt.toml", "benchs/**/*"]
[dev-dependencies]
criterion = "0.5.1"

[dependencies]
clap = { version = "4.5.4", features = ["derive"]}
lazy_static = "1.5.0"
pest = "2.1.3"
pest_derive = "2.1.0"
regex = "1.5.4"
rayon = "1.5.1"
serde_json = "1.0.133"
colored_json = "5.0.0"
toml = "0.8.19"

[[bench]]
name = "benchmark"
harness = false

[lib]
name = "kjql"
path = "src/lib.rs"

[[bin]]
name = "kjql"
path = "src/bin.rs"